{
    "KPlugin": {
        "Authors": [
            {
                "Email": "onet.cristian@gmail.com",
                "Name": "Cristian Oneț"
            }
        ],
        "Description": "Exports schedules to iCalendar files",
        "Description[ar]": "تصدّر الجداول إلى ملفّات iCalendar",
        "Description[bs]": "Izvozi rasporede u iCalendar datoteke",
        "Description[ca@valencia]": "Exporta les programacions als fitxers de l'iCalendar",
        "Description[ca]": "Exporta les programacions als fitxers de l'iCalendar",
        "Description[da]": "Eksporterer skemaer til iCalendar-filer",
        "Description[de]": "Exportiert geplante Buchungen in iCalendar-Dateien",
        "Description[el]": "Εξαγωγή ημερολογίων σε αρχεία iCalendar",
        "Description[en_GB]": "Exports schedules to iCalendar files",
        "Description[es]": "Exporta programaciones a archivos de iCalendar",
        "Description[et]": "Ajakavade eksport iCalendari failidena",
        "Description[eu]": "Programazioak iCalendar-en fitxategietara esportatzen ditu",
        "Description[fi]": "Vie aikataulut iCalendar-tiedostoihin",
        "Description[fr]": "Exportes des calendriers dans des fichiers « iCalendar »",
        "Description[gl]": "Exporta planificacións a ficheiros iCalendar",
        "Description[hu]": "Exportálja az időbeosztásokat iCalendar fájlokba",
        "Description[it]": "Esporta pianificazioni in file iCalendar",
        "Description[kk]": "Кестелерін iCalendar файлдарына экспорттау",
        "Description[nds]": "Planen as iCalendar-Dateien exporteren",
        "Description[nl]": "Exporteert planningen naar iCalender bestanden",
        "Description[pl]": "Eksportuje harmonogramy do plików iCalendar",
        "Description[pt]": "Exporta os calendários para ficheiros iCalendar",
        "Description[pt_BR]": "Exporta os calendários para arquivos iCalendar",
        "Description[ro]": "Exportă tranzacțiile programate în fișiere iCalendar",
        "Description[ru]": "Экспорт плана платежей в файл iCalendar",
        "Description[sk]": "Exportovať rozvrhy do súborov iCalendar",
        "Description[sv]": "Exporterar scheman till iCalendar-filer",
        "Description[tr]": "Zamanlamaları iCalendar dosyalarına aktarır",
        "Description[uk]": "Експортує розклади до файлів iCalendar",
        "Description[x-test]": "xxExports schedules to iCalendar filesxx",
        "Description[zh_TW]": "匯出排程到 iCalendar 檔",
        "EnabledByDefault": true,
        "Icon": "x-office-calendar",
        "Id": "icalendarexporter",
        "License": "GPL",
        "Name": "iCalendar",
        "Name[bs]": "iCalendar",
        "Name[ca@valencia]": "iCalendar",
        "Name[ca]": "iCalendar",
        "Name[cs]": "iCalendar",
        "Name[da]": "iCalendar",
        "Name[de]": "iCalendar",
        "Name[el]": "iCalendar",
        "Name[en_GB]": "iCalendar",
        "Name[es]": "iCalendar",
        "Name[et]": "iCalendar",
        "Name[eu]": "iCalendar",
        "Name[fi]": "iCalendar",
        "Name[fr]": "iCalendar",
        "Name[ga]": "iCalendar",
        "Name[gl]": "iCalendar",
        "Name[hu]": "iCalendar",
        "Name[ia]": "iCalendar",
        "Name[it]": "iCalendar",
        "Name[kk]": "iCalendar",
        "Name[lt]": "iCalendar",
        "Name[nds]": "iCalendar",
        "Name[nl]": "iCalendar",
        "Name[pl]": "iCalendar",
        "Name[pt]": "iCalendar",
        "Name[pt_BR]": "iCalendar",
        "Name[ro]": "iCalendar",
        "Name[ru]": "iCalendar",
        "Name[sk]": "iCalendar",
        "Name[sv]": "iCalendar",
        "Name[tr]": "iCalendar",
        "Name[ug]": "iCalendar",
        "Name[uk]": "iCalendar",
        "Name[x-test]": "xxiCalendarxx",
        "Name[zh_CN]": "iCalendar",
        "Name[zh_TW]": "iCalendar",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
