# default KDE build env
include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/json-validation.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      - /gitlab-templates/craft-appimage.yml
      - /gitlab-templates/craft-windows-x86-64.yml
#      - /gitlab-templates/craft-macos-arm64.yml
#      - /gitlab-templates/craft-macos-x86-64.yml

# macos installs currently only on demand since they are failing
craft_macos_arm64:
  when: manual

craft_macos_x86_64:
  when: manual

# appimage and windows are currently broken due to changes in craft
# that do not support Qt5 builds anymore. Switched to manual execution.
craft_appimage_qt515_x86_64:
  when: manual

craft_windows_qt515_x86_64:
  when: manual

# custom builds

build_local_ubuntu_2110:
# make it manual for now, since 21.10 alkimia is at 5.7 and as such incompatible with master
  when: manual
  stage: build
  image: ubuntu:21.10
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - echo "Installing dependencies."
    - apt update
    - sed -i -- 's/#[ ]*deb-src/deb-src/g' /etc/apt/sources.list
    - apt update
    - apt install -y apt-utils eatmydata
    - eatmydata apt build-dep -y kmymoney
    - eatmydata apt install -y libsqlcipher-dev libqt5sql5-sqlite qtbase5-private-dev ninja-build

  script:
    - echo "Building."
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - ninja

distro_kf5_leap:
  stage: build
  #when: manual
  image: rhabacker/suse_leap_kf5_qt515
  variables:
    ci_parallel: "16"
    ci_sudo: "yes"
    ci_variant: "kf5"
  before_script:
    - ./tools/ci-install.sh
  script:
    - ./tools/ci-build.sh

distro_kf6_tumbleweed:
  stage: build
  # don't stop pipeline if this job fails
  allow_failure: true
  #when: manual
  image: rhabacker/suse_tumbleweed_kf6_qt68
  variables:
    ci_parallel: "16"
    ci_sudo: "yes"
    ci_variant: "kf6"
  before_script:
    - ./tools/ci-install.sh
  script:
    - ./tools/ci-build.sh
