# default KDE build env
include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/windows.yml

# custom builds
build_local_ubuntu_2004:
  # make it manual for now, since it constantly fails due to the lack of QWebengine support
  when: manual
  stage: build
  image: ubuntu:20.04
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - echo "Installing dependencies."
    - sed -i -- 's/#[ ]*deb-src/deb-src/g' /etc/apt/sources.list
    - apt update
    - apt install -y apt-utils eatmydata
    - eatmydata apt build-dep -y kmymoney
    - eatmydata apt install -y qt5-default libsqlcipher-dev libqt5sql5-sqlite qtbase5-private-dev ninja-build

  script:
    - echo "Building."
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - ninja

build_local_ubuntu_2110:
  # make it manual for now, since it constantly fails
  when: manual
  stage: build
  image: ubuntu:21.10
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  before_script:
    - echo "Installing dependencies."
    - apt update
    - sed -i -- 's/#[ ]*deb-src/deb-src/g' /etc/apt/sources.list
    - apt update
    - apt install -y apt-utils eatmydata
    - eatmydata apt build-dep -y kmymoney
    - eatmydata apt install -y libsqlcipher-dev libqt5sql5-sqlite qtbase5-private-dev ninja-build

  script:
    - echo "Building."
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug
    - ninja

