# SPDX-FileCopyrightText: 2022 Thomas Baumgart <tbaumgart@kde.org>
# SPDX-FileCopyrightText: 2022 Dawid Wróbel <me@dawidwrobel.com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kholidays': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'graphics/kdiagram': '@stable'
# Temporarily removed because out of a sudden: "Package akonadi was not found in branch release/23.08"
#    'pim/akonadi': '@stable'
# Temporarily removed because out of a sudden: "Package kidentitymanagement was not found in branch release/23.08"
#    'pim/kidentitymanagement': '@stable'
    'office/alkimia': '@latest'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
  cmake-options: '-DWARNINGS_AS_ERRORS=on -Werror=dev'
