# SPDX-FileCopyrightText: 2022 Thomas Baumgart <tbaumgart@kde.org>
# SPDX-FileCopyrightText: 2022 Dawid Wróbel <me@dawidwrobel.com>
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt5', 'FreeBSD/Qt5', 'Windows/Qt5']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcmutils': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/kguiaddons': '@stable'
    'frameworks/kholidays': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kwindowsystem': '@stable'
    'frameworks/kxmlgui': '@stable'
    'graphics/kdiagram': '@stable'
# Temporarily removed because out of a sudden: "Package akonadi was not found in branch release/23.08"
#    'pim/akonadi': '@stable'
# Temporarily removed because out of a sudden: "Package kidentitymanagement was not found in branch release/23.08"
#    'pim/kidentitymanagement': '@stable'
    'office/alkimia': '@latest'

- 'on': ['Linux/Qt6', 'FreeBSD/Qt6', 'Windows/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kcompletion': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kguiaddons': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/kitemviews': '@latest-kf6'
    'frameworks/ktextwidgets': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'
    'frameworks/kxmlgui': '@latest-kf6'
    'graphics/kdiagram': '@latest-kf6'
    'office/alkimia': '@latest-kf6'
    'pim/akonadi': '@latest-kf6'
    'pim/kidentitymanagement': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
  cmake-options: '-DWARNINGS_AS_ERRORS=on -Werror=dev'
