# SPDX-FileCopyrightText: 2024, 2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kmymoney
confinement: strict
grade: stable
base: core24
adopt-info: kmymoney
version: 5.2.0
apps:
  kmymoney:
    extensions:
      - kde-neon
    common-id: org.kde.kmymoney.desktop
    desktop: usr/share/applications/org.kde.kmymoney.desktop
    command: usr/bin/kmymoney
    plugs:
      - home
      - audio-playback
      - browser-support
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kmymoney
    bus: session
parts:
  libgpgmepp-qt5:
    build-packages:
      - libassuan-dev
      - libgpg-error-dev
      - qtchooser
      - rsync
    stage-packages:
      - libassuan0
      - libgpg-error0
    source: https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-1.23.2.tar.bz2
    source-checksum: sha256/9499e8b1f33cccb6815527a1bc16049d35a6198a6c5fae0185f2bd561bce5224
    plugin: autotools
    autotools-configure-parameters:
      - --disable-gpgsm-test
      - --enable-languages=cpp,qt5
      - --prefix=/usr
      - --enable-fixed-path=/snap/kde-qt5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-environment: &buildenvironment
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/kde-qt5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:/snap/kf5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr
      - PKG_CONFIG_PATH: /snap/kde-qt5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  gwenhywfar:
    after:
      - libgpgmepp-qt5
    source: https://github.com/aqbanking/gwenhywfar.git
    source-tag: 5.12.0
    plugin: autotools
    build-packages:
      - gettext
      - libgcrypt20-dev
      - libgnutls28-dev
    stage-packages:
      - libgcrypt20
      - libgnutls30t64
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-guis=none
  mpir:
    source: https://github.com/wbhart/mpir.git
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --enable-cxx=yes
    build-packages:
      - yasm
      - texinfo
      - rsync
    override-build: |
      craftctl default
      rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  libplasma:
    plugin: cmake
    source: https://invent.kde.org/plasma/libplasma.git
    source-branch: kf5
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_DESKTOPTHEMES=OFF
      - -DBUILD_TESTING=OFF
    build-environment:
      - CMAKE_PREFIX_PATH: $CRAFT_STAGE/usr:/snap/kde-qt5--sdk/current/usr:/snap/kf5-core24-sdk/current/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
      - LD_LIBRARY_PATH: >
         "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt5-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    build-packages:
      - libxcb-composite0-dev
      - libxcb-damage0-dev
      - libxcb-shape0-dev
      - libxcb-glx0-dev
      - libvulkan-dev
      - libxkbcommon-dev
      - libwayland-dev
      - doxygen
      - gettext
      - graphviz
      - pkg-config
      - libgl-dev
      - libgl1-mesa-dev
      - libgles-dev
      - libglvnd-dev
      - libglx-dev
      - libegl-dev
      - libsm-dev
      - docbook
      - docbook-xml
      - docbook-xsl
  alkimia:
    after:
      - mpir
      - libplasma
    source: https://invent.kde.org/office/alkimia.git
    source-branch: 8.2
    plugin: cmake
    build-packages:
      - libpulse0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=5
      - -DBUILD_WITH_QT5=ON
      - -DBUILD_TESTING=OFF
      - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kde-qt5-core24-sdk/current\\;/snap/kf5-core24-sdk/current/usr"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kde-qt5-core24-sdk/current\\;/snap/kf5-core24-sdk/current/usr"
    build-environment: *buildenvironment
  kmymoney:
    after:
      - libgpgmepp-qt5
      - gwenhywfar
      - alkimia
    parse-info:
      - usr/share/metainfo/org.kde.kmymoney.appdata.xml
    plugin: cmake
    source: https://download.kde.org/stable/kmymoney/5.2.0/kmymoney-5.2.0.tar.xz
    build-packages:
      - libofx-dev
      - libsqlcipher-dev
      - libaqbanking-dev
      - python3-dev
      - libharfbuzz-subset0
    stage-packages:
      - libofx7t64
      - libsqlcipher1
      - libaqbanking44
      - libharfbuzz-subset0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=5
      - -DBUILD_WITH_QT5=ON
      - -DBUILD_TESTING=OFF
      - "-DCMAKE_FIND_ROOT_PATH=$CRAFT_STAGE\\;/snap/kde-qt5-core24-sdk/current\\;/snap/kf5-core24-sdk/current/usr"
      - "-DCMAKE_PREFIX_PATH=$CRAFT_STAGE\\;/snap/kde-qt5-core24-sdk/current\\;/snap/kf5-core24-sdk/current/usr"
    build-environment: *buildenvironment
    stage:
      - -usr/share/gwenhywfar/gwenbuild/builders/posix/sharedlib.gwb
      - -usr/share/gwenhywfar/typemaker2/c/char_array.tm2
      - -usr/share/gwenhywfar/typemaker2/c/double.tm2
      - -usr/share/locale/de/LC_MESSAGES/gwenhywfar.mo
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
  cleanup:
    after:
      - kmymoney
    plugin: nil
    build-snaps:
      - core24
      - kf5-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf5-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done

