{
    "KPlugin": {
        "Authors": [
            {
                "Email": "christian-david@web.de",
                "Name": "Christian Dávid",
                "Name[ca@valencia]": "Christian Dávid",
                "Name[ca]": "Christian Dávid",
                "Name[cs]": "Christian Dávid",
                "Name[en_GB]": "Christian Dávid",
                "Name[es]": "Christian Dávid",
                "Name[fr]": "Christian Dávid",
                "Name[gl]": "Christian Dávid",
                "Name[it]": "Christian Dávid",
                "Name[nl]": "Christian Dávid",
                "Name[pl]": "Christian Dávid",
                "Name[pt]": "Christian Dávid",
                "Name[pt_BR]": "Christian Dávid",
                "Name[ru]": "Christian Dávid",
                "Name[sk]": "Christian Dávid",
                "Name[sv]": "Christian Dávid",
                "Name[uk]": "Christian Dávid",
                "Name[x-test]": "xxChristian Dávidxx"
            }
        ],
        "Description": "Adds predefined IBAN/BIC numbers to KMyMoney",
        "Description[ca@valencia]": "Afig números IBAN/BIC predefinits al KMyMoney",
        "Description[ca]": "Afegeix números IBAN/BIC predefinits al KMyMoney",
        "Description[en_GB]": "Adds predefined IBAN/BIC numbers to KMyMoney",
        "Description[es]": "Añade números IBAN/BIC predefinidos a KMyMoney",
        "Description[fr]": "Ajoute des numéros IBAN/BIC prédéfinis à KMyMoney",
        "Description[gl]": "Engade números predefinidos de IBAN e BIC a KMyMoney",
        "Description[it]": "Aggiunge i numeri IBAN/BIC predefiniti a KMyMoney",
        "Description[ko]": "KMyMoney에 미리정의된 IBAN/BIC 번호를 추가",
        "Description[nl]": "Voegt voorgedefinieerde IBAN/BIC-nummers toe aan KMyMoney",
        "Description[pl]": "Dodaje uprzednio określone numery IBAN/BIC do KMyMoney",
        "Description[pt]": "Adiciona os números IBAN/BIC predefinidos ao KMyMoney",
        "Description[pt_BR]": "Adiciona números IBAN/BIC pré-definidos no KMyMoney",
        "Description[sv]": "Lägger till fördefinierade IBAN/BIC-nummer i KMyMoney",
        "Description[uk]": "Попередньо визначені номери IBAN/BIC у KMyMoney",
        "Description[x-test]": "xxAdds predefined IBAN/BIC numbers to KMyMoneyxx",
        "EnabledByDefault": true,
        "Icon": "server-database",
        "Id": "ibanbicdata",
        "License": "GPL",
        "Name": "IBAN/BIC Data",
        "Name[ca@valencia]": "Dades IBAN i BIC",
        "Name[ca]": "Dades IBAN i BIC",
        "Name[en_GB]": "IBAN/BIC Data",
        "Name[es]": "Datos IBAN/BIC",
        "Name[fr]": "Données IBAN/BIC",
        "Name[gl]": "Datos de IBAN e BIC",
        "Name[it]": "Dati IBAN/BIC",
        "Name[nl]": "IBAN/BIC gegevens",
        "Name[pl]": "Dane IBAN/BIC",
        "Name[pt]": "Dados do IBAN/BIC",
        "Name[pt_BR]": "Dados IBAN/BIC",
        "Name[sv]": "IBAN- och BIC-data",
        "Name[uk]": "Дані IBAN та BIC",
        "Name[x-test]": "xxIBAN/BIC Dataxx",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
