{
    "KPlugin": {
        "Authors": [
            {
                "Email": "mte@users.sourceforge.net",
                "Name": "Michael Edwardes",
                "Name[ca@valencia]": "Michael Edwardes",
                "Name[ca]": "Michael Edwardes",
                "Name[cs]": "Michael Edwardes",
                "Name[de]": "Michael Edwardes",
                "Name[en_GB]": "Michael Edwardes",
                "Name[es]": "Michael Edwardes",
                "Name[eu]": "Michael Edwardes",
                "Name[fr]": "Michael Edwardes",
                "Name[gl]": "Michael Edwardes",
                "Name[it]": "Michael Edwardes",
                "Name[nl]": "Michael Edwardes",
                "Name[pl]": "Michael Edwardes",
                "Name[pt]": "Michael Edwardes",
                "Name[pt_BR]": "Michael Edwardes",
                "Name[ru]": "Michael Edwardes",
                "Name[sk]": "Michael Edwardes",
                "Name[sv]": "Michael Edwardes",
                "Name[uk]": "Michael Edwardes",
                "Name[x-test]": "xxMichael Edwardesxx"
            }
        ],
        "Description": "Add GnuCash importing to KMyMoney",
        "Description[ca@valencia]": "Afig la importació des de GnuCash al KMyMoney",
        "Description[ca]": "Afegeix la importació des del GnuCash al KMyMoney",
        "Description[en_GB]": "Add GnuCash importing to KMyMoney",
        "Description[es]": "Añade importación GnuCash a KMyMoney",
        "Description[eu]": "GnuCash inportazioa gehitzen dio KMyMoneyri ",
        "Description[fr]": "Ajoute l'importation « GnuCash » à KMyMoney",
        "Description[gl]": "Engadir a posibilidade de importar GnuCash en KMyMoney",
        "Description[it]": "Aggiunge l'importazione GnuCash a KMymoney",
        "Description[ko]": "KMyMoney에 GnuCash 가져오기 추가",
        "Description[nl]": "Voeg GnuCash importeren toe aan KMyMoney",
        "Description[pl]": "Dodaje importowanie GnuCash do KMyMoney",
        "Description[pt]": "Adição da importação do GnuCash para o KMyMoney",
        "Description[pt_BR]": "Adiciona importação GnuCash no KMyMoney",
        "Description[sk]": "Pridať GnuCash import do KMyMoney",
        "Description[sv]": "Lägg till GnuCash-import till KMyMoney",
        "Description[uk]": "Імпортування даних GnuCash у KMyMoney",
        "Description[x-test]": "xxAdd GnuCash importing to KMyMoneyxx",
        "EnabledByDefault": true,
        "Icon": "document-import",
        "Id": "gncimporter",
        "License": "GPL",
        "Name": "GNC Importer",
        "Name[ca@valencia]": "Importador de GNC",
        "Name[ca]": "Importador de GNC",
        "Name[de]": "GNC-Import",
        "Name[en_GB]": "GNC Importer",
        "Name[es]": "Importador GNC",
        "Name[eu]": "OFX inportatzailea",
        "Name[fr]": "Importateur GNC",
        "Name[gl]": "Importador de GNC",
        "Name[it]": "Strumento di importazione GNC",
        "Name[nl]": "GNC-importprogramma",
        "Name[pl]": "Importer GNC",
        "Name[pt]": "Importação de GNC",
        "Name[pt_BR]": "Importador GNC",
        "Name[ru]": "Импорт GNC",
        "Name[sk]": "GNC Importer",
        "Name[sv]": "GNC-import",
        "Name[uk]": "Імпортування GNC",
        "Name[x-test]": "xxGNC Importerxx",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
