{
    "KPlugin": {
        "Authors": [
            {
                "Email": "ktambascio@users.sourceforge.net,tbaumgart@kde.org,acejones@users.sourceforge.net,lukasz.wojnilowicz@gmail.com",
                "Name": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[ca@valencia]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[ca]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[de]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[en_GB]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[es]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[et]": "Kevin Tambascio, Thomas Baumgart, Ace Jones, Łukasz Wojniłowicz",
                "Name[eu]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[fi]": "Kevin Tambascio, Thomas Baumgart, Ace Jones, Łukasz Wojniłowicz",
                "Name[fr]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[gl]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[ia]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[it]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[ko]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[nl]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[pl]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[pt]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[pt_BR]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[ru]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[sk]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[sl]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[sv]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[uk]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz",
                "Name[x-test]": "xxKevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowiczxx",
                "Name[zh_CN]": "Kevin Tambascio,Thomas Baumgart,Ace Jones,Łukasz Wojniłowicz"
            }
        ],
        "Description": "Adds XML storage support to KMyMoney",
        "Description[ca@valencia]": "Afig la implementació de l'emmagatzematge en XML a KMyMoney",
        "Description[ca]": "Afegeix la implementació de l'emmagatzematge en XML al KMyMoney",
        "Description[en_GB]": "Adds XML storage support to KMyMoney",
        "Description[es]": "Añade almacenamiento XML a KMyMoney",
        "Description[et]": "KMyMoney XML-salvesti toetus",
        "Description[eu]": "XML biltegiratze euskarria gehitzen dio KMyMoneyri",
        "Description[fi]": "Lisää KMyMoneyyn XML-varastotuen",
        "Description[fr]": "Ajoute la prise en charge du stockage « XML » à KMyMoney",
        "Description[gl]": "Engade a posibilidade de almacenamento de XML en KMyMoney",
        "Description[ia]": "Adde supporto de immagazinage de XML a KMyMoney",
        "Description[it]": "Aggiunge il supporto per l'archiviazione XML a KMyMoney",
        "Description[ko]": "KMyMoney에 XML 저장소 지원 추가",
        "Description[nl]": "Voegt ondersteuning toe voor XML-opslag aan KMyMoney",
        "Description[pl]": "Dodaje obsługę pamięci XML do KMyMoney",
        "Description[pt]": "Adiciona o suporte do armazenamento em XML ao KMyMoney",
        "Description[pt_BR]": "Adiciona suporte ao armazenamento XML no KMyMoney",
        "Description[ru]": "Добавляет в KMyMoney поддержку хранения данных в формате XML",
        "Description[sk]": "Pridáva podporu XML úložiska do KMyMoney",
        "Description[sl]": "Dodaj programu KMyMoney podporo za shranjevanje XML",
        "Description[sv]": "Lägger till stöd för XML-lagring i KMyMoney",
        "Description[uk]": "Підтримка сховищ XML у KMyMoney",
        "Description[x-test]": "xxAdds XML storage support to KMyMoneyxx",
        "Description[zh_CN]": "为 KMyMoney 添加 XML 存储支持",
        "EnabledByDefault": true,
        "Icon": "server-database",
        "Id": "xmlstorage",
        "License": "GPL",
        "Name": "XML Storage",
        "Name[ca@valencia]": "Emmagatzematge XML",
        "Name[ca]": "Emmagatzematge XML",
        "Name[de]": "XML-Speicher",
        "Name[en_GB]": "XML Storage",
        "Name[es]": "Almacenamiento XML",
        "Name[et]": "XML-salvesti",
        "Name[eu]": "XML biltegiratzea",
        "Name[fi]": "XML-varasto",
        "Name[fr]": "Stockage XML",
        "Name[gl]": "Almacenamento de XML",
        "Name[ia]": "Immagazinage XML",
        "Name[it]": "Archiviazione XML",
        "Name[ko]": "XML 저장소",
        "Name[nl]": "XML-opslag",
        "Name[pl]": "Pamięć XML",
        "Name[pt]": "Armazenamento em XML",
        "Name[pt_BR]": "Armazenamento XML",
        "Name[ru]": "Сохранение XML",
        "Name[sk]": "XML Úložisko",
        "Name[sl]": "Shramba XML",
        "Name[sv]": "XML-lagring",
        "Name[uk]": "Сховище XML",
        "Name[x-test]": "xxXML Storagexx",
        "Name[zh_CN]": "XML 存储",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    },
    "X-KDE-ConfigModule": "kmymoney/kcm_xmlstorage"
}
