{
    "KPlugin": {
        "Authors": [
            {
                "Email": "mte@users.sourceforge.net",
                "Name": "Michael Edwardes",
                "Name[x-test]": "xxMichael Edwardesxx"
            }
        ],
        "Description": "Add QIF exporting to KMyMoney",
        "Description[ca@valencia]": "Afig l'exportació cap a QIF a KMyMoney",
        "Description[ca]": "Afegeix l'exportació a QIF al KMyMoney",
        "Description[de]": "Fügt QIF-Export zu KMyMoney hinzu",
        "Description[eo]": "Aldoni QIF-eksportadon al KMyMoney",
        "Description[es]": "Añade exportación QIF a KMyMoney",
        "Description[et]": "KMyMoney QIF eksportimine",
        "Description[eu]": "QIF esportazioa gehitzen dio KMyMoneyri ",
        "Description[fi]": "Lisää KMyMoneyyn QIF-viennin",
        "Description[fr]": "Ajoute l'exportation « QIF » à KMyMoney",
        "Description[gl]": "Engadir a posibilidade de exportar QIF desde KMyMoney",
        "Description[it]": "Aggiunge l'esportazione QIF a KMymoney",
        "Description[ka]": "KMyMoney-ში QIF გატანის დამატება",
        "Description[ko]": "KMyMoney에 QIF 내보내기 추가",
        "Description[nb]": "Legge til eksport av QIF i KMyMoney",
        "Description[nl]": "Voeg QIF exporteren toe aan KMyMoney",
        "Description[pl]": "Dodaje eksportowanie QIF do KMyMoney",
        "Description[pt]": "Adição da exportação para QIF para o KMyMoney",
        "Description[pt_BR]": "Adiciona exportação QIF no KMyMoney",
        "Description[ru]": "Добавляет в KMyMoney возможность экспорта QIF",
        "Description[sk]": "Pridať QIF export do KMyMoney",
        "Description[sl]": "Dodaj v KMyMoney možnost izvoza QIF",
        "Description[sv]": "Lägg till QIF-export till KMyMoney",
        "Description[uk]": "Експортування даних QIF у KMyMoney",
        "Description[x-test]": "xxAdd QIF exporting to KMyMoneyxx",
        "Description[zh_CN]": "为 KMyMoney 添加 QIF 导出服务",
        "Description[zh_TW]": "提供 QIF 匯出功能給 KMyMoney",
        "EnabledByDefault": true,
        "Icon": "document-export",
        "Id": "qifexporter",
        "License": "GPL",
        "Name": "QIF Exporter",
        "Name[ca@valencia]": "Exportador a QIF",
        "Name[ca]": "Exportador a QIF",
        "Name[de]": "QIF-Export",
        "Name[eo]": "QIF-Eksportilo",
        "Name[es]": "Exportador QIF",
        "Name[et]": "QIF eksportija",
        "Name[eu]": "QIF esportatzailea",
        "Name[fi]": "QIF-vienti",
        "Name[fr]": "Exportateur QIF",
        "Name[gl]": "Exportador a QIF",
        "Name[ia]": "Exportator de QIF",
        "Name[it]": "Strumento di esportazione QIF",
        "Name[ka]": "QIF გამტანი",
        "Name[ko]": "QIF 내보내기 도구",
        "Name[nb]": "QIF-eksport",
        "Name[nl]": "QIF exporteren",
        "Name[pl]": "Eksporter QIF",
        "Name[pt]": "Exportação para QIF",
        "Name[pt_BR]": "Exportador QIF",
        "Name[ru]": "Экспорт QIF",
        "Name[sl]": "Izvoznik QIF",
        "Name[sv]": "QIF-export",
        "Name[tr]": "QIF Dışa Aktarıcısı",
        "Name[uk]": "Інструмент експортування QIF",
        "Name[x-test]": "xxQIF Exporterxx",
        "Name[zh_CN]": "QIF 导出工具",
        "Name[zh_TW]": "QIF 匯出工具",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    },
    "X-KDE-ConfigModule": "kmymoney/kcm_qif"
}
