{
    "KPlugin": {
        "Authors": [
            {
                "Email": "romain@symlink.me",
                "Name": "Romain Bignon",
                "Name[ca@valencia]": "Romain Bignon",
                "Name[ca]": "Romain Bignon",
                "Name[cs]": "Romain Bignon",
                "Name[de]": "Romain Bignon",
                "Name[en_GB]": "Romain Bignon",
                "Name[es]": "Romain Bignon",
                "Name[et]": "Romain Bignon",
                "Name[eu]": "Romain Bignon",
                "Name[fi]": "Romain Bignon",
                "Name[fr]": "Romain Bignon",
                "Name[gl]": "Romain Bignon",
                "Name[ia]": "Romain Bignon",
                "Name[it]": "Romain Bignon",
                "Name[ko]": "Romain Bignon",
                "Name[nl]": "Romain Bignon",
                "Name[pl]": "Romain Bignon",
                "Name[pt]": "Romain Bignon",
                "Name[pt_BR]": "Romain Bignon",
                "Name[ru]": "Romain Bignon",
                "Name[sk]": "Romain Bignon",
                "Name[sl]": "Romain Bignon",
                "Name[sv]": "Romain Bignon",
                "Name[uk]": "Romain Bignon",
                "Name[x-test]": "xxRomain Bignonxx",
                "Name[zh_CN]": "Romain Bignon"
            }
        ],
        "Description": "Plugin for Woob",
        "Description[ca]": "Connector per al Woob",
        "Description[cs]": "Modul Woob",
        "Description[es]": "Complemento para Woob",
        "Description[fr]": "Module externe pour Woob",
        "Description[ko]": "Woob용 플러그인",
        "Description[nl]": "Plug-in voor Woob",
        "Description[pt_BR]": "Plugin para Woob",
        "Description[sl]": "Vtičnik za Woob",
        "Description[sv]": "Insticksprogram för Woob",
        "Description[uk]": "Додаток для Woob",
        "Description[x-test]": "xxPlugin for Woobxx",
        "EnabledByDefault": true,
        "Icon": "network-connect",
        "Id": "woob",
        "License": "GPL",
        "Name": "Woob",
        "Name[ca]": "Woob",
        "Name[cs]": "Woob",
        "Name[es]": "Woob",
        "Name[fr]": "Woob",
        "Name[ko]": "Woob",
        "Name[nl]": "Woob",
        "Name[pt_BR]": "Woob",
        "Name[sl]": "Woob",
        "Name[sv]": "Woob",
        "Name[uk]": "Woob",
        "Name[x-test]": "xxWoobxx",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
