{
    "KPlugin": {
        "Authors": [
            {
                "Email": "aganders93@gmail.com",
                "Name": "Allan Anderson",
                "Name[ca@valencia]": "Allan Anderson",
                "Name[ca]": "Allan Anderson",
                "Name[cs]": "Allan Anderson",
                "Name[de]": "Allan Anderson",
                "Name[en_GB]": "Allan Anderson",
                "Name[es]": "Allan Anderson",
                "Name[et]": "Allan Anderson",
                "Name[fr]": "Allan Anderson",
                "Name[gl]": "Allan Anderson",
                "Name[it]": "Allan Anderson",
                "Name[nl]": "Allan Anderson",
                "Name[pl]": "Allan Anderson",
                "Name[pt]": "Allan Anderson",
                "Name[pt_BR]": "Allan Anderson",
                "Name[ru]": "Allan Anderson",
                "Name[sk]": "Allan Anderson",
                "Name[sv]": "Allan Anderson",
                "Name[uk]": "Allan Anderson",
                "Name[x-test]": "xxAllan Andersonxx"
            }
        ],
        "Description": "Add CSV exporting to KMyMoney",
        "Description[ca@valencia]": "Afig l'exportació a CSV al KMyMoney",
        "Description[ca]": "Afegeix l'exportació a CSV al KMyMoney",
        "Description[de]": "Fügt CSV-Export zu KMyMoney hinzu",
        "Description[en_GB]": "Add CSV exporting to KMyMoney",
        "Description[es]": "Añade exportación CSV a KMyMoney",
        "Description[et]": "KMyMoney CVS eksportimine",
        "Description[fr]": "Ajoute l'exportation « CSV » à KMyMoney",
        "Description[gl]": "Engadir a posibilidade de exportar CSV desde KMyMoney",
        "Description[it]": "Aggiunge l'esportazione CSV a KMymoney",
        "Description[ko]": "KMyMoney에 CSV 내보내기를 추가",
        "Description[nl]": "Voeg CSV exporteren toe aan KMyMoney",
        "Description[pl]": "Dodaje eksportowanie CSV do KMyMoney",
        "Description[pt]": "Adição da exportação para CSV para o KMyMoney",
        "Description[pt_BR]": "Adiciona exportação CSV no KMyMoney",
        "Description[sk]": "Pridať CSV exportovanie do KMyMoney",
        "Description[sv]": "Lägg till CSV-export till KMyMoney",
        "Description[uk]": "Експортування даних CSV у KMyMoney",
        "Description[x-test]": "xxAdd CSV exporting to KMyMoneyxx",
        "EnabledByDefault": true,
        "Icon": "document-export",
        "Id": "csvexporter",
        "License": "GPL",
        "Name": "CSV Exporter",
        "Name[ca@valencia]": "Exportador a CSV",
        "Name[ca]": "Exportador a CSV",
        "Name[cs]": "Exportér CSV",
        "Name[de]": "CSV-Export",
        "Name[en_GB]": "CSV Exporter",
        "Name[es]": "Exportador CSV",
        "Name[et]": "CVS eksportija",
        "Name[fr]": "Exportateur de CSV",
        "Name[gl]": "Exportador a CSV",
        "Name[it]": "Strumento di esportazione CSV",
        "Name[nl]": "CSV-exportprogramma",
        "Name[pl]": "Eksporter CSV",
        "Name[pt]": "Exportação para CSV",
        "Name[pt_BR]": "Exportador CSV",
        "Name[ru]": "Экспорт CSV",
        "Name[sk]": "CSV exportér",
        "Name[sv]": "CSV-export",
        "Name[uk]": "Експортування CSV",
        "Name[x-test]": "xxCSV Exporterxx",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
