{
    "KPlugin": {
        "Authors": [
            {
                "Email": "tonybloom@users.sourceforge.net,lukasz.wojnilowicz@gmail.com",
                "Name": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[ca@valencia]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[ca]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[en_GB]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[es]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[fr]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[gl]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[it]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[nl]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[pl]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[pt]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[pt_BR]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[ru]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[sv]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[uk]": "Tony Bloomfield,Łukasz Wojniłowicz",
                "Name[x-test]": "xxTony Bloomfield,Łukasz Wojniłowiczxx"
            }
        ],
        "Description": "Adds SQL storage support to KMyMoney",
        "Description[ca@valencia]": "Afig la implementació de l'emmagatzematge en SQL al KMyMoney",
        "Description[ca]": "Afegeix la implementació de l'emmagatzematge en SQL al KMyMoney",
        "Description[en_GB]": "Adds SQL storage support to KMyMoney",
        "Description[es]": "Añade almacenamiento SQL a KMyMoney",
        "Description[fr]": "Ajoute la prise en charge du stockage « SQL » à KMyMoney",
        "Description[gl]": "Engade a posibilidade de almacenamento de SQL en KMyMoney",
        "Description[it]": "Aggiunge il supporto di archiviazione a KMyMoney",
        "Description[ko]": "KMyMoney에 SQL 스토리지 지원 추가",
        "Description[nl]": "Voegt ondersteuning toe voor SQL-opslag aan KMyMoney",
        "Description[pl]": "Dodaje obsługę pamięci SQL do KMyMoney",
        "Description[pt]": "Adiciona o suporte do armazenamento em SQL ao KMyMoney",
        "Description[pt_BR]": "Adiciona suporte ao armazenamento SQL no KMyMoney",
        "Description[sv]": "Lägger till stöd för SQL-lagring i KMyMoney",
        "Description[uk]": "Підтримка сховища даних SQL у KMyMoney",
        "Description[x-test]": "xxAdds SQL storage support to KMyMoneyxx",
        "EnabledByDefault": true,
        "Icon": "server-database",
        "Id": "sqlstorage",
        "License": "GPL",
        "Name": "SQL Storage",
        "Name[ca@valencia]": "Emmagatzematge SQL",
        "Name[ca]": "Emmagatzematge SQL",
        "Name[cs]": "Úložiště SQL",
        "Name[en_GB]": "SQL Storage",
        "Name[es]": "Almacenamiento SQL",
        "Name[fr]": "Stockage SQL",
        "Name[gl]": "Almacenamento de SQL",
        "Name[it]": "Archiviazione SQL",
        "Name[nl]": "SQL-opslag",
        "Name[pl]": "Pamięć SQL",
        "Name[pt]": "Armazenamento em SQL",
        "Name[pt_BR]": "Armazenamento SQL",
        "Name[sv]": "SQL-lagring",
        "Name[uk]": "Сховище SQL",
        "Name[x-test]": "xxSQL Storagexx",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
