{
    "KPlugin": {
        "Authors": [
            {
                "Email": "aganders93@gmail.com,lukasz.wojnilowicz@gmail.com",
                "Name": "Allan Anderson,Łukasz Wojniłowicz"
            }
        ],
        "Description": "Add CSV importing to KMyMoney",
        "Description[ar]": "أضف استيراد CSV إلى أموالك",
        "Description[bs]": "Dodaj uvoz CSV za KMyMoney",
        "Description[ca@valencia]": "Afig la importació CSV al KMyMoney",
        "Description[ca]": "Afegeix la importació CSV al KMyMoney",
        "Description[da]": "Føj CSV-import til KMyMoney",
        "Description[de]": "Fügt CSV-Import zu KMyMoney hinzu",
        "Description[el]": "Προσθήκη εισαγωγής CSV στο KMyMoney",
        "Description[en_GB]": "Add CSV importing to KMyMoney",
        "Description[es]": "Añade la importación de CSV a KMyMoney",
        "Description[et]": "CSV import KMyMoneysse",
        "Description[eu]": "Erantsi CSV-ren inportazioa KMyMoney-ri",
        "Description[fi]": "Lisää CSV-tuonti KMyMoney-ohjelmaan",
        "Description[fr]": "Ajoute l'importation « CVS » à KMyMoney",
        "Description[gl]": "Engadir importación de CSV ao KMyMoney",
        "Description[hu]": "CSV hozzáadása a KMyMoney-ba importáláshoz",
        "Description[it]": "Aggiungi l'importazione CSV a KMyMoney",
        "Description[kk]": "CSV файлды KMyMoney-ге импорттап қосу",
        "Description[lt]": "Įdėti CSV importavimą į KMyMoney",
        "Description[nds]": "CSV-Import för KMyMoney",
        "Description[nl]": "Voeg CSV importeren toe aan KMyMoney",
        "Description[pl]": "Dodaje importowanie CSV do KMyMoney",
        "Description[pt]": "Adição da importação de CSV ao KMyMoney",
        "Description[pt_BR]": "Adiciona a importação de CSV ao KMyMoney",
        "Description[ro]": "Importă fișier csv (câmpuri separate de virgulă) în KMyMoney",
        "Description[ru]": "Импорт CSV в KMyMoney",
        "Description[sk]": "Pridať CSV importovanie do KMyMoney",
        "Description[sv]": "Lägg till CSV-import till KMyMoney",
        "Description[tr]": "KMyMoney'e CSV aktarımı ekle",
        "Description[uk]": "Додає можливість імпортування CSV до KMyMoney",
        "Description[x-test]": "xxAdd CSV importing to KMyMoneyxx",
        "Description[zh_TW]": "匯入 CSV 檔到 KMyMoney",
        "EnabledByDefault": true,
        "Icon": "document-import",
        "Id": "csvimporter",
        "License": "GPL",
        "Name": "CSV Importer",
        "Name[ar]": "استيراد CSV",
        "Name[bs]": "csvimport",
        "Name[ca@valencia]": "csvimport",
        "Name[ca]": "csvimport",
        "Name[cs]": "csvimport",
        "Name[da]": "csvimport",
        "Name[de]": "CSV-Import",
        "Name[el]": "csvimport",
        "Name[en_GB]": "csvimport",
        "Name[es]": "csvimport",
        "Name[et]": "CSV import",
        "Name[eu]": "csvimport",
        "Name[fi]": "csvimport",
        "Name[fr]": "Importation « csv »",
        "Name[ga]": "csvimport",
        "Name[gl]": "csvimport",
        "Name[hu]": "csvimport",
        "Name[it]": "csvimport",
        "Name[kk]": "csvimport",
        "Name[lt]": "csvimport",
        "Name[nds]": "CSV-Import",
        "Name[nl]": "csvimport",
        "Name[pl]": "Importowanie CSV",
        "Name[pt]": "csvimport",
        "Name[pt_BR]": "csvimport",
        "Name[ro]": "csvimport",
        "Name[ru]": "csvimport",
        "Name[sk]": "csvimport",
        "Name[sv]": "CSV-import",
        "Name[tr]": "csvimport",
        "Name[uk]": "csvimport",
        "Name[x-test]": "xxcsvimportxx",
        "Name[zh_CN]": "csv 导入",
        "Name[zh_TW]": "csvimport",
        "ServiceTypes": [
            "KMyMoney/Plugin"
        ],
        "Version": "@PROJECT_VERSION@@PROJECT_VERSION_SUFFIX@",
        "Website": "https://kmymoney.org/plugins.html"
    }
}
