
FIND_PATH(CPPUNIT_INCLUDE_DIR
  TestSuite.h PATH_SUFFIXES cppunit )

FIND_LIBRARY(CPPUNIT_LIBRARY
  NAMES cppunit-1.12 cppunit )

IF(CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)
  SET(CPPUNIT_FOUND on)
ENDIF(CPPUNIT_INCLUDE_DIR AND CPPUNIT_LIBRARY)

MARK_AS_ADVANCED(CPPUNIT_INCLUDE_DIR CPPUNIT_LIBRARY)
